Solving 2 issues on generateEventName function
PiwikPRO/server-side-template-for-gtm-v2-client pull request #9
Opened 2024-11-11 12:03 UTC by OphelieMicoine

goal_conversion as page_view event
Consider Content impression and interaction request

2024-11-22 12:06 UTC, anthonybartczak commented on template.tpl
> -
Let's keep that part in the template just in case Google introduces client template gallery at some point

2024-11-22 12:41 UTC, abartczakpiwik requested changes

2024-11-22 12:41 UTC, abartczakpiwik commented on template.tpl
> -﻿___TERMS_OF_SERVICE___
Let's keep that part in the template just in case Google introduces client template gallery at some point.

2024-11-22 12:41 UTC, abartczakpiwik commented on template.tpl
>    } else if (requestData.idgoal) {
@sahava was there a reason why we added goal conversions so low in the event detection pipeline?

> The first thing the tracker does to detect the type of event it’s dealing with is look for signs that the event resulted in a conversion. If the tracked event has an &idgoal parameter with a value other than 0, it is classified as Goal conversion

https://help.piwik.pro/support/questions/what-are-events-and-how-are-they-detected/#step-1:-goal-conversion

Looking at the docs - I'd move it to the top and change the condition:

```javascript
const generateEventName = (requestData) => {
  if (requestData.event_name) {
    return requestData;
  } else if (requestData.idgoal && requestData.idgoal !== 0) {
    requestData.event_name = 'goal_conversion';
  } else if (requestData.ping) {
    requestData.event_name = 'ping';
  } else if (requestData.c_i) {
    requestData.event_name = 'content_interaction';
  } else if (requestData.c_n) {
    requestData.event_name = 'content_impression';
  } else if (requestData.e_t) {
    requestData.event_name = requestData.e_t;
  } else if (requestData.e_c) {
    requestData.event_name = requestData.e_c;
  } else if (requestData.search) {
    requestData.event_name = 'search';
  } else if (requestData.link) {
    requestData.event_name = 'click';
  } else if (requestData.download) {
    requestData.event_name = 'file_download';
  } else if (requestData.action_name) {
    requestData.event_name = 'page_view';
  }  else {
    requestData.event_name = DEFAULT_EVENT_NAME;
  }
  return requestData;
};
```

2024-11-25 11:29 UTC, abartczakpiwik approved these changes

2025-01-02 10:59 UTC, abartczakpiwik commented
@OphelieMicoine due to Piwik PRO public repository requirements, please sign your commits before we do the merge.

- [Generating a new GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
- [Signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)
- [Telling Git about your signing key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key)

Feel free to reach out to me (e.g. on LI) in case you need help with that

2025-01-02 13:56 UTC, OphelieMicoine commented
Hello @abartczakpiwik ! My last commit is signed. Is it solving the merge issue ?

Happy New Year !!!

2025-01-02 14:01 UTC, abartczakpiwik commented
> Hello @abartczakpiwik ! My last commit is signed. Is it solving the merge issue ?
> 
> Happy New Year !!!

Sadly it has to be applied to all of the previous commits :(

IMO the fastest way to do this is to:
1. `git rebase --exec 'git commit --amend --no-edit -S' -i HEAD~3` where `3` is the amount of commits you'd like to address
2. Change `pick` to `reword`
3. After saving `git push origin solving-issues-on-generateEventName-function --force`

Happy New Year :)

2025-01-02 15:20 UTC, OphelieMicoine commented
I did it ^^

Thanks for the clear guidelines.

2025-01-08 10:18 UTC, merged